# Generated by Django 3.0.8 on 2020-08-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketballevent',
            old_name='event_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='basketballevent',
            old_name='event_type',
            new_name='league',
        ),
    ]
