# Generated by Django 3.0.8 on 2020-07-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TennisEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField()),
                ('event_status', models.CharField(default='Scheduled', max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('match_id', models.CharField(max_length=100)),
                ('participant1', models.CharField(max_length=100)),
                ('participant2', models.CharField(max_length=100)),
                ('event_score', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
